### ISSUE TITLE
pkg_resources 不存在

### ISSUE THREAD

**Issue by cpken** [megvii-research/megactor#17]
执行安装时报如下错误，无法安装成功。

```

Collecting deepspeed==0.14.0 (from -r requirements.txt (line 45))
  Using cached http://mirrors.aliyun.com/pypi/packages/c4/d2/8ef74ea43580db602b845a499340ee21da98fb1e749d86ab9ee16bc32bd2/deepspeed-0.14.0.tar.gz (1.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-zexh_7v5/deepspeed_e4085a8fbf4c4e5da3ba7539a6357fd5/setup.py", line 100, in <module>
          cuda_major_ver, cuda_minor_ver = installed_cuda_version()
        File "/tmp/pip-install-zexh_7v5/deepspeed_e4085a8fbf4c4e5da3ba7539a6357fd5/op_builder/builder.py", line 47, in installed_cuda_version
          import torch.utils.cpp_extension
        File "megactor/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 25, in <module>
          from pkg_resources import packaging  # type: ignore[attr-defined]
      ImportError: cannot import name 'packaging' from 'pkg_resources' (/megactor/lib/python3.10/site-packages/pkg_resources/__init__.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by lhd777** [comment]
请查看另一个issue来安装detectron2 & detectron2-densepose：
https://github.com/megvii-research/megactor/issues/11

**Comment by 6AlexMan** [comment]
you can use my conda config.maybe it can help you

`name: megactor-ok
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - binutils_impl_linux-64=2.40=ha1999f0_7
  - binutils_linux-64=2.40=hb3c18ed_4
  - blas=2.16=mkl
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - cpython=3.10.15=py310hd8ed1ab_2
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cuda-version=12.6=3
  - cudatoolkit-dev=11.7.0=h1de0b5d_6
  - freetype=2.12.1=h267a509_2
  - gcc_impl_linux-64=11.4.0=h00c12a0_13
  - gcc_linux-64=11.4.0=ha077dfb_4
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py310he8512ff_2
  - gxx_impl_linux-64=11.4.0=h634f3ee_13
  - gxx_linux-64=11.4.0=h35bfe5d_4
  - intel-openmp=2022.0.1=h06a4308_3633
  - jinja2=3.1.4=pyhd8ed1ab_0
  - kernel-headers_linux-64=3.10.0=he073ed8_17
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - lerc=4.0.0=h27087fc_0
  - libblas=3.8.0=16_mkl
  - libcblas=3.8.0=16_mkl
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.77=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.22=hb9d3cd8_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-devel_linux-64=11.4.0=h8f596e0_113
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libgomp=14.2.0=h77fa898_1
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.8.0=16_mkl
  - liblapacke=3.8.0=16_mkl
  - libnpp=11.7.4.75=0
  - libnsl=2.0.1=hd590300_0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.44=hadc24fc_0
  - libsanitizer=11.4.0=h5763a12_13
  - libsqlite=3.46.1=hadc24fc_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-devel_linux-64=11.4.0=h8f596e0_113
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.7.0=he137b08_1
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - mkl=2020.2=256
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_0
  - ncurses=6.5=he02047a_1
  - networkx=3.4.2=pyhd8ed1ab_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.3.2=hb9d3cd8_0
  - pip=24.2=pyh8b19718_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - python=3.10.15=h4a871b0_2_cpython
  - python_abi=3.10=5_cp310
  - pytorch=2.0.0=py3.10_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h8228510_1
  - sympy=1.13.3=pyh2585a3b_104
  - sysroot_linux-64=2.17=h4a8ded7_17
  - tk=8.6.13=noxft_h4845f30_101
  - torchtriton=2.0.0=py310
  - typing_extensions=4.12.2=pyha770c72_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xz=5.2.6=h166bdaf_0
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.1.0
      - accelerate==0.24.1
      - addict==2.4.0
      - aiofiles==23.2.1
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.6.2.post1
      - argparse==1.4.0
      - asttokens==2.4.1
      - audio-augmentations==0.1.3
      - augment==0.4
      - av==13.1.0
      - awscli==1.29.62
      - black==24.10.0
      - botocore==1.31.62
      - braceexpand==0.1.7
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - chumpy==0.70
      - click==8.1.7
      - clip==1.0
      - cloudpickle==3.1.0
      - cmake==3.28.1
      - colorama==0.4.4
      - coloredlogs==15.0.1
      - comm==0.2.2
      - contourpy==1.3.0
      - crcmod==1.7
      - cryptography==43.0.3
      - cycler==0.12.1
      - cython==3.0.11
      - decorator==4.4.2
      - deepspeed==0.14.2
      - detectron2==0.6
      - detectron2-densepose==0.6
      - diffusers==0.27.2
      - docutils==0.16
      - einops==0.7.0
      - essentia==2.1b6.dev1110
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastapi==0.115.2
      - ffmpeg==1.4
      - ffmpy==0.4.0
      - filelock==3.14.0
      - flatbuffers==24.3.25
      - fonttools==4.54.1
      - fsspec==2024.10.0
      - ftfy==6.3.0
      - fvcore==0.1.5.post20221221
      - gradio==4.44.1
      - gradio-client==1.3.0
      - grpcio==1.67.0
      - h11==0.14.0
      - hf-transfer==0.1.6
      - hjson==3.1.0
      - httpcore==1.0.6
      - httpx==0.27.2
      - huggingface-hub==0.23.2
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.36.0
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iopath==0.1.9
      - ipython==8.28.0
      - ipywidgets==8.1.5
      - jedi==0.19.1
      - jmespath==0.10.0
      - json-tricks==3.17.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lit==17.0.6
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mmengine==0.10.5
      - model-index==0.1.11
      - moviepy==1.0.3
      - munkres==1.1.4
      - mypy-extensions==1.0.0
      - ninja==1.11.1.1
      - nose==1.3.7
      - numpy==1.26.3
      - omegaconf==2.3.0
      - onnx==1.16.0
      - onnxruntime-gpu==1.16.0
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.10.0.84
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.0.11
      - ordered-set==4.1.0
      - ordereddict==1.1
      - orjson==3.10.9
      - oss2==2.17.0
      - packaging==24.1
      - pandas==2.2.3
      - parso==0.8.4
      - pathlib==1.0.1
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pillow==10.4.0
      - pillow-avif-plugin==1.4.6
      - platformdirs==4.3.6
      - portalocker==2.10.1
      - proglog==0.1.10
      - prompt-toolkit==3.0.48
      - protobuf==5.28.2
      - psutil==6.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyasn1==0.6.1
      - pycocotools==2.0.8
      - pycparser==2.22
      - pycryptodome==3.21.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydub==0.25.1
      - pyfacer==0.0.4
      - pygments==2.18.0
      - pynvml==11.5.3
      - pyparsing==3.2.0
      - pyre-extensions==0.0.29
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.12
      - pytz==2023.4
      - pyyaml==6.0.2
      - refile==0.4.1
      - regex==2024.9.11
      - requests==2.32.3
      - rich==13.4.2
      - rsa==4.7.2
      - ruff==0.7.0
      - s3transfer==0.7.0
      - safetensors==0.4.1
      - scikit-image==0.24.0
      - scipy==1.14.1
      - semantic-version==2.10.0
      - setuptools==60.2.0
      - shapely==2.0.6
      - shellingham==1.5.4
      - six==1.16.0
      - sniffio==1.3.1
      - stack-data==0.6.3
      - starlette==0.40.0
      - tabulate==0.9.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.5.0
      - terminaltables==3.1.10
      - tifffile==2024.9.20
      - timm==0.9.12
      - tokenizers==0.13.3
      - tomli==2.0.2
      - tomlkit==0.12.0
      - torchaudio==2.0.1
      - torchvision==0.15.1+cu117
      - tqdm==4.65.2
      - traitlets==5.14.3
      - transformers==4.31.0
      - typer==0.12.5
      - typing-inspect==0.9.0
      - tzdata==2024.2
      - urllib3==2.0.7
      - uvicorn==0.32.0
      - validators==0.34.0
      - wcwidth==0.2.13
      - webdataset==0.2.86
      - websockets==12.0
      - werkzeug==3.0.4
      - widgetsnbextension==4.0.13
      - xformers==0.0.19
      - xtcocotools==1.14.3
      - yacs==0.1.8
      - yapf==0.40.2
      - zipp==3.20.2
`

**Comment by 6AlexMan** [comment]
you should delete "- clip==1.0" from the above config。And download ‘CLIP-main.zip’ and pip install it :)

**Comment by 6AlexMan** [comment]
```yaml
detectron2==0.6
detectron2-densepose==0.6
```
you use pip to install the above module by https://github.com/megvii-research/megactor/issues/17#issuecomment-2196252131
